version: '3'

services:
  update_configs:
    build: ../common/ruby
#    build:
#      context: ../common/ruby
#      dockerfile: Dockerfile-dev
#    command: bash -c "sleep infinity"
    command: bash -c "/usr/share/base/ruby/bin/update_config.rb peer-node && touch /state/update_configs"

    environment:
    - S3_PEERS_FILE=s3://symbol-testnet/testnet-0941-v1/peer-list/peers-p2p.json

    volumes:
    - ../common/ruby:/usr/share/base/ruby
    - ./runtime-vars:/usr/share/base/ruby/config
    - ./peer-node:/usr/share/base/peer-node
    - ./rest-gateway:/usr/share/base/rest-gateway
    - ./state:/state:rw

  ###### running services ###########

  peer-node:
    image: techbureau/catapult-server:gcc-0.9.4.1
    ports:
    - 7900:7900
#    command: bash -c "sleep infinity"
    command: bash -c "/bin-mount/wait /state/update_configs && /bin/bash /userconfig/runServerRecover.sh && /bin/bash /userconfig/startServer.sh"
    stop_signal: SIGINT
    restart: on-failure:2
    volumes:
    - ../utilities/bin/bash:/bin-mount
    - ./peer-node/userconfig:/userconfig/
    - ./data:/data:rw
    - ./state:/state:rw
    - ./data/debug:/usr/share/apport/apport:rw
