run_time_vars:
- name: BOOT_PRIVATE_KEY
  source:
    key: boot_private_key
    address_position: 0 
    key_type: private
  targets:
  - peer-node/userconfig/resources/config-user.properties
- name: PUBLIC_KEY
  source:
    key: public_key
    address_position: 0 
    key_type: public
  targets: []
- name: HARVESTER_PRIVATE_KEY
  source:
    key: harvester_private_key
    # using same key as use for BOOT_PRIVATE_KEY
    address_position: 0 
    key_type: private
    donot_overwrite: true
  targets:
  - peer-node/userconfig/resources/config-harvesting.properties
- name: FRIENDLY_NAME
  source:
    type: friendly_name
    key: friendly_name
    address_position: 0 
    key_type: public
  targets:
  - peer-node/userconfig/resources/config-node.properties
