run_time_vars:
- name: BOOT_PRIVATE_KEY
  source:
    key: boot_private_key
    address_position: 0 
    key_type: private
  targets:
  - api-node/userconfig/resources/config-user.properties

- name: PUBLIC_KEY
  source:
    key: public_key
    address_position: 0 
    key_type: public
  targets:
  - rest-gateway/userconfig/rest.json

- name: FRIENDLY_NAME
  source:
    type: friendly_name
    key: friendly_name
    address_position: 0 
    key_type: public
    donot_overwrite: true
  targets:
  - api-node/userconfig/resources/config-node.properties

