run_time_vars:
- name: BOOT_PRIVATE_KEY
  source:
    path: api-node/config-input.yaml
    key: boot_private_key
    address_position: 0 
    key_type: private
  targets:
  - api-node/userconfig/resources/config-user.properties
  - api-node/userconfig/resources/config-harvesting.properties 
- name: PUBLIC_KEY
  source:
    path: api-node/config-input.yaml
    key: public_key
    address_position: 0 
    key_type: public
  targets:
  - rest-gateway/userconfig/rest.json

- name: FRIENDLY_NAME
  source:
    type: friendly_name
    path: api-node/config-input.yaml
    key: friendly_name
    address_position: 0 
    key_type: public
  targets:
  - api-node/userconfig/resources/config-node.properties

- name: HARVEST_PRIVATE_KEY
  source:
    path: api-node/config-input.yaml
    key: harvest_private_key
    address_position: 0 
    key_type: private
  targets:
  - api-node/userconfig/resources/config-harvesting.properties 
- name: HARVEST_BENEFICIARY_PUBLIC_KEY
  source:
    path: api-node/config-input.yaml
    key: harvest_beneficiary_public_key
    address_position: 0 
    key_type: public
  targets:
  - api-node/userconfig/resources/config-harvesting.properties 
